### ISSUE TITLE
Fix the coin amount check

### ISSUE THREAD

**Issue by Hatsuney** [Mikuia/Mikuia#25]
Commands with coin cost work even if you don't have enough coins, you just go into negative numbers...

**Comment by Maxorq** [comment]
probably fixed with 890d699f67b479762d77125b4d54438e14a52a78

**Comment by Hatsuney** [comment]
definitely fixed with bd33e47ec963cdd35541bb206300eb0b2cbfb9d5

**Comment by Hatsuney** [comment]
lol

**Comment by vendethiel** [comment]
should 890d699 be reverted?

**Comment by Hatsuney** [comment]
lol no why

**Comment by vendethiel** [comment]
dunno

**Comment by Hatsuney** [comment]
it was a different bug lol
