### ISSUE TITLE
Unable to delete an account

### ISSUE THREAD

**Issue by CVex2150J** [Mikuia/Mikuia#35]
Hi, I just check in your source code to see if it's possible to delete a twitch accout from the database and did't find anything. I checked because I want to remove mine from mikuia.tv and there is no place that I can find to do that on the dashboard/profile page/etc...  It's should be nice to have the possibility to completely delete an account with a big warning to inform the user that all levels and associated data will be lost.

**Comment by Hatsuney** [comment]
orrr you can just ask me for that
