### ISSUE TITLE
I can't log in with Twitch

### ISSUE THREAD

**Issue by Seamob** [Mikuia/Mikuia#48]
Yeah thats pretty much it.. everytime i try to click "Authorize", it sends me to a page with some error message:
{"status":401,"message":"invalid csrf token"}
https://i.imgur.com/c8qOALX.png
help pls?

**Comment by lauriys** [comment]
i assume you've tried at least twice; this usually happens when you attempt to login to two apps at the same time

**Comment by Seamob** [comment]
oops
._.
