### ISSUE TITLE
Add themes/skin structure

### ISSUE THREAD

**Issue by michaelowens** [Mikuia/Mikuia#8]
This way Mikuia can use the Metronic skin (paid) and forks can use a different theme.

Shouldn't be too hard to do, because Metronic is based on Bootstrap. First version could be copy of templates, remove all custom CSS/JS and add Bootstrap. See from there what else is necessary.

I can take a look at this tomorrow.

**Comment by Hatsuney** [comment]
I think it's clear to say that this won't happen any time soon.
